- name: 添加服務使用者 'mysql' 到 {{ ansible_host }}
  user:
    name: mysql
    shell: /sbin/nologin
    create_home: no

- name: 添加 mysql 群組給 {{ user_name }}
  user: 
    name: "{{ user_name }}"
    groups: mysql
    append: yes
  
- name: 安裝啟動 mysql 缺少的檔案 
  yum:
    name: libaio
    state: present
  
- name: 下載 mysql 安裝包到 {{ ansible_host }}
  get_url:
    url: https://dl.fromer.url/mysql-5.7.34-el7-x86_64.tar.gz
    dest: /data/dl
    username: yidevops
    password: Log@n0vu3

- name: 解壓 mysql 安裝包到 {{ ansible_host }}
  unarchive:
    src: /data/dl/mysql-5.7.34-el7-x86_64.tar.gz
    dest: /data
    remote_src: yes

- name: 重新命名 mysql 資料夾
  shell:
    cmd: mv mysql-5.7.34-el7-x86_64 mysql
    chdir: /data

- name: 添加 mysql 需要的資料夾
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /data/mysql/data
  - /data/mysql/logs
  - /data/mysql/mysqld
  - /data/mysql/binlog
  - /etc/my.cnf.d

- name: 更改 mysql 權限
  file:
    path: /data/mysql/
    owner: mysql
    group: mysql
    recurse: true

- name: 上傳 master.cnf 到 /etc/my.cnf.d/
  copy:
    src: "master.cnf"
    dest: "/etc/my.cnf.d"

- name: 上傳 mysql_env.sh 到 /etc/profile.d
  copy:
    src: "mysql_env.sh"
    dest: "/etc/profile.d"

- name: 上傳 my.cnf 到 /etc
  copy:
    src: "my.cnf"
    dest: "/etc"

- name: 上傳 systemd 檔案到 {{ ansible_host }}
  copy:
    src: "mysqld.service"
    dest: "/etc/systemd/system"
  
- name: systemd daemon-reload enable mysql
  systemd:
    daemon_reload: yes
    enabled: yes
    name: mysqld

- name: 初始化 mysql
  shell:
    cmd: /data/mysql/bin/mysqld --initialize --user=mysql --basedir=/data/mysql --datadir=/data/mysql/data

- name: 清理 /data/dl/mysql-5.7.34-el7-x86_64.tar.gz
  file:
    path: /data/dl/mysql-5.7.34-el7-x86_64.tar.gz
    state: absent
