- name: close redis on hltd-redis-1
  hosts: hltd-redis-1
  gather_facts: false
  remote_user: "{{ ansible_user }}"
  become: yes
  tasks:
   - name: kill redis
     shell: ps -ef |grep "redis-server" |awk '{print $2}' | xargs kill -9

- name: close redis on hltd-redis-2
  hosts: hltd-redis-2
  gather_facts: false
  remote_user: "{{ ansible_user }}"
  become: yes
  tasks:
   - name: kill redis
     shell: ps -ef |grep "redis-server" |awk '{print $2}' | xargs kill -9