- name: install zabbix-agent2 on desired host
  hosts: "{{ hosts_name }}" 
  remote_user: "{{ ansible_user }}"
  become: yes
  tasks:      
    - debug: msg="{{ inventory_hostname }}"  

    - name: install zabbix-agent2 yum resources
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

    - name: clean yum cache
      shell: yum clean all
      args:
        warn: no

    - name: install zabbix-agent2
      yum:
        name: zabbix-agent2
        state: present

# TODO: zabbix-agent2.conf should be update by file(such as template or copy paste) in future

    - name: change /etc/zabbix-agent2.conf Server address
      shell: sed -i 's,Server=54.254.89.225,Server=[host ip],g' /etc/zabbix/zabbix_agent2.conf
      args:
        warn: no

    - name: change /etc/zabbix-agent2.conf ServerActive address
      shell: sed -i 's,ServerActive=54.254.89.225,ServerActive=[host ip],g' /etc/zabbix/zabbix_agent2.conf
      args:
        warn: no

    - name: change /etc/zabbix-agent2.conf Hostname
      shell: sed -i 's,Hostname=Zabbix server,Hostname={{ inventory_hostname }},g' /etc/zabbix/zabbix_agent2.conf
      args:
        warn: no

    - name: stop zabbix-agent2(for one shot)
      systemd:
        name: zabbix-agent2
        state: stopped

    - name: enable & start zabbix-agent2
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: started

    - name: check zabbix-agent2 running
      shell: systemctl status zabbix-agent2
      register: status

    - debug: var=status.stdout_lines
