- name: 添加服務使用者 'kafka' 到 {{ ansible_host }}
  user:
    name: kafka
    shell: /sbin/nologin
    create_home: no

- name: 下載 kafka_exporter 安裝包到 {{ ansible_host }}
  get_url:
    url: https://dl.fromer.url/kafka_exporter-1.2.0.linux-amd64.tar.gz
    dest: /data/dl
    username: yidevops
    password: Log@n0vu3

- name: 解壓 kafka_expoter 安裝包到 {{ ansible_host }}
  unarchive:
    src: /data/dl/kafka_exporter-1.2.0.linux-amd64.tar.gz
    dest: /data
    remote_src: yes

- name: 重新命名 kafka_exporter 資料夾
  shell:
    cmd: mv kafka_exporter-1.2.0.linux-amd64 kafka_exporter
    chdir: /data/

- name: 更改 kafka_exporter 權限
  file:
    path: /data/kafka_exporter/
    owner: kafka
    group: kafka
    recurse: true

- name: 上傳 systemd 檔案到 {{ ansible_host }}
  copy:
    src: "kafka_exporter.service"
    dest: "/etc/systemd/system"

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: 清理 /data/dl/kafka_exporter-1.2.0.linux-amd64.tar.gz
  file:
    path: /data/dl/kafka_exporter-1.2.0.linux-amd64.tar.gz
    state: absent
